### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by andreykuzovlevv** [eloialonso/diamond#10]
## Error when run python play.py
python play.py
Traceback (most recent call last):
  File "C:\Users\thegr\Saved Games\diamond\src\play.py", line 148, in <module>
    main()
  File "C:\Users\thegr\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\Saved Games\diamond\src\play.py", line 141, in main
    env, keymap = prepare_dataset_mode(cfg) if args.dataset_mode else prepare_play_mode(cfg, args)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\Saved Games\diamond\src\play.py", line 83, in prepare_play_mode
    path_ckpt = get_path_agent_ckpt("checkpoints", epoch=-1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\Saved Games\diamond\src\utils.py", line 205, in get_path_agent_ckpt
    assert len(all_) >= -epoch
           ^^^^^^^^^^^^^^^^^^^
AssertionError

___

## Changes before
Before this was
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'checkpoints\\agent_versions'
so i created diamond\src\checkpoints\agent_versions

also I changed gymnasium[atari,accept-rom-license]==0.29.1 with gymnasium==0.29.1 in requirements.txt becouse of:
ERROR: Cannot install shimmy[atari]==0.1.0, shimmy[atari]==0.2.0 and shimmy[atari]==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    shimmy[atari] 0.2.1 depends on ale-py~=0.8.1; extra == "atari"
    shimmy[atari] 0.2.0 depends on ale-py~=0.8.0; extra == "atari"
    shimmy[atari] 0.1.0 depends on ale-py~=0.8.0; extra == "atari"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by andreykuzovlevv** [comment]
i forgot git checkout csgo

**Comment by andreykuzovlevv** [comment]
i forgot git checkout csgo
